In [6]:
import os
import cv2
import torchvision

In [18]:
capture = cv2.VideoCapture("not_attentive-2.mp4")
os.makedirs("NA2_Test_Frames", exist_ok=True)

In [19]:
frame_count = 300 #int(capture.get(cv2.CAP_PROP_FRAME_COUNT))
count = 0
i = 0
retaining = True
arr = []
capture = cv2.VideoCapture("not_attentive-2.mp4")
while count < frame_count and retaining:
    retaining, frame = capture.read()
    if frame is None:
        continue
    frame = cv2.resize(frame, (256,256))
    arr.append(frame)
    cv2.imwrite(filename=os.path.join("NA2_Test_Frames", '{}.jpg'.format(str(i))), img=frame)
    i += 1
    count+=1
capture.release()

In [88]:
img = cv2.imread("Test_Frames/0.jpg")

img.shape

(256, 256, 3)

In [40]:
import torch
import transforms

def load_model_and_test(model_name, test_path):
    model_loaded = torch.load(model_name) 
    model_loaded.eval()
    transformer=torchvision.transforms.Compose([transforms.VideoFolderPathToTensor()])
    transformed = transformer(test_path)
    transformed = transformed.cuda()
    return model_loaded(transformed.unsqueeze(0))

In [39]:
print(load_model_and_test("model.pt",os.path.join(os.getcwd(), "A_Test_Frames")),
    load_model_and_test("model-aug.pt",os.path.join(os.getcwd(), "A_Test_Frames")),
    load_model_and_test("model-v2.pt",os.path.join(os.getcwd(), "A_Test_Frames")))

tensor([[-3.1345, -1.3844,  4.7970,  0.4885]], device='cuda:0',
       grad_fn=<AddmmBackward0>) tensor([[-3.6529, -0.3956,  3.4343,  0.2015]], device='cuda:0',
       grad_fn=<AddmmBackward0>) tensor([[-4.1266, -1.9213,  5.1119,  0.6839]], device='cuda:0',
       grad_fn=<AddmmBackward0>)


In [16]:
print(load_model_and_test("model.pt",os.path.join(os.getcwd(), "NA_Test_Frames")),
    load_model_and_test("model-aug.pt",os.path.join(os.getcwd(), "NA_Test_Frames")),
    load_model_and_test("model-v2.pt",os.path.join(os.getcwd(), "NA_Test_Frames")))

tensor([[-2.2744, -2.1154,  4.8632,  0.5693]], device='cuda:0',
       grad_fn=<AddmmBackward0>) tensor([[-3.9617, -0.9388,  4.5669, -0.1978]], device='cuda:0',
       grad_fn=<AddmmBackward0>) tensor([[-1.1270, -3.2207,  2.6952,  0.7034]], device='cuda:0',
       grad_fn=<AddmmBackward0>)


In [21]:
print(load_model_and_test("model.pt",os.path.join(os.getcwd(), "NA2_Test_Frames")),
    load_model_and_test("model-aug.pt",os.path.join(os.getcwd(), "NA2_Test_Frames")),
    load_model_and_test("model-v2.pt",os.path.join(os.getcwd(), "NA2_Test_Frames")))

tensor([[-2.2647,  0.4216,  3.3362, -0.8334]], device='cuda:0',
       grad_fn=<AddmmBackward0>) tensor([[-3.0005, -0.8041,  0.5108,  3.8707]], device='cuda:0',
       grad_fn=<AddmmBackward0>) tensor([[-2.5865, -1.6734,  2.4280,  1.6015]], device='cuda:0',
       grad_fn=<AddmmBackward0>)


In [14]:
# load_model_and_test("model-v2.pt",os.path.join(os.getcwd(), "A_Test_Frames"))

In [108]:
def key_function(s):
    # Use a regular expression to find numeric parts in the string
    import re
    s = os.path.split(s)[1]
    numeric_part = re.search(r'\d+', s)
    if numeric_part:
        return int(numeric_part.group())  # Convert the numeric part to an integer
    else:
        return float('inf')

In [102]:
path = os.path.join(os.getcwd(), "A_Test_Frames")
file_names = sorted([os.path.join(path, f) for f in os.listdir(path) if os.path.isfile(os.path.join(path, f))])

In [110]:
path = os.path.join(os.getcwd(), "A_Test_Frames")
file_names = sorted([os.path.join(path, f) for f in os.listdir(path) if os.path.isfile(os.path.join(path, f))], key=key_function)

In [ ]:
# use_cuda = True
# device = torch.device("cuda" if use_cuda else "cpu")
# model_loaded.eval()
# inputs = torch.randn([1, 30, 3, 256, 256]).to(device)
# model_loaded(inputs)

In [22]:
import pandas as pd

In [36]:
train_df = pd.read_csv("Test.csv")

In [37]:
train_df["label"].value_counts()

label
2    882
3    814
1     84
0      4
Name: count, dtype: int64

In [38]:
len(train_df)

1784

In [31]:
# print("""label
# 2    2617
# 3    2494
# 0     34
# 1     213""")
train_df["label"].value_counts()

label
2    2617
3    2494
0     34
1     213


In [32]:
train_df.head()

Unnamed: 0.1  Unnamed: 0                                          path  \
0             0         0.0  DAiSEE/DataSet/TrainFrames/310071/3100711049   
1             1         1.0  DAiSEE/DataSet/TrainFrames/310071/3100712014   
2             2         2.0  DAiSEE/DataSet/TrainFrames/310071/3100711043   
3             3         3.0  DAiSEE/DataSet/TrainFrames/310071/3100711007   
4             4         4.0  DAiSEE/DataSet/TrainFrames/310071/3100711042   

   label  
0      2  
1      2  
2      3  
3      2  
4      2

In [33]:
train_df.drop(["Unnamed: 0.1","Unnamed: 0"], axis=1, inplace=True) 

In [35]:
train_df.head()

path  label
0  DAiSEE/DataSet/TrainFrames/310071/3100711049      2
1  DAiSEE/DataSet/TrainFrames/310071/3100712014      2
2  DAiSEE/DataSet/TrainFrames/310071/3100711043      3
3  DAiSEE/DataSet/TrainFrames/310071/3100711007      2
4  DAiSEE/DataSet/TrainFrames/310071/3100711042      2

In [50]:
import torch
import transforms

def load_model_and_test(model_name, test_path):
    model_loaded = torch.load(model_name) 
    model_loaded.eval()
    transformer=torchvision.transforms.Compose([transforms.VideoFolderPathToTensor()])
    transformed = transformer(test_path)
    transformed = transformed.cuda()
    return model_loaded(transformed.unsqueeze(0))

In [51]:
print(load_model_and_test("model-v2.pt",os.path.join(os.getcwd(), "A_Test_Frames")))

tensor([[-4.1266, -1.9213,  5.1119,  0.6839]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
