In [1]:
import torchvision
from torch.utils.data import DataLoader

/home/sethupat/.conda/envs/ELIR-p39/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [8]:
import datasets
import transforms

def generate_dataloader(batch_size, csv, root):
    dataset = datasets.VideoDataset(csv,
                                    root,
                                    transform=torchvision.transforms.Compose([transforms.VideoFolderPathToTensor()]))

    return DataLoader(dataset,
                      batch_size=batch_size,
                      shuffle=True,
                      num_workers=2)


def get_dataloader(batch_size, csv_train, root_train, csv_test, root_test):
    return {
        'train': generate_dataloader(batch_size, csv_train, root_train),
        'test': generate_dataloader(batch_size, csv_test, root_test)}

In [3]:
# os.chdir(os.path.join(os.getcwd(),'elearning-teaching-intervention-recommender'))

import torch
# Check if CUDA (GPU support) is available
if torch.cuda.is_available():
    # Get the current device (GPU or CPU)
    current_device = torch.cuda.current_device()
    
    # Get the name of the current device
    device_name = torch.cuda.get_device_name(current_device)
    
    print(f"Using GPU: {device_name}")
else:
    print("CUDA (GPU support) is not available. Using CPU.")

# Create a tensor and check the device it's on
x = torch.tensor([1.0])
if x.is_cuda:
    print("x is on GPU.")
else:
    print("x is on CPU.")

Using GPU: NVIDIA GeForce GTX 1080
x is on CPU.


In [ ]:
import os
from torch.optim.lr_scheduler import StepLR
from tqdm import tqdm
import torch
from torch import nn, optim
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score

import numpy as np

# from ResTCN import ResTCN
from ResTCN import ResTCN

torch.manual_seed(0)
num_epochs = 100
batch_size = 4
lr = .001
use_cuda = True
device = torch.device("cuda" if use_cuda else "cpu")
print("Device being used:", device, flush=True)


dataloader = get_dataloader(batch_size,
                            'Train.csv',
                            os.path.join(os.getcwd()),
                            'Test.csv',
                            os.path.join(os.getcwd()))
dataset_sizes = {x: len(dataloader[x].dataset) for x in ['train', 'test']}
print(dataset_sizes, flush=True)


model = ResTCN().to(device)
# optimizer = optim.Adam(model.parameters(), lr=lr)
optimizer = optim.SGD(model.parameters(), lr=lr, momentum=0.9)
scheduler = StepLR(optimizer, step_size=50, gamma=.1)

criterion = nn.CrossEntropyLoss().to(device)
softmax = nn.Softmax()

for epoch in range(num_epochs):

    for phase in ['train', 'test']:

        running_loss = .0
        y_trues = np.empty([0])
        y_preds = np.empty([0])

        if phase == 'train':
            model.train()
        else:
            model.eval()

        for inputs, labels in tqdm(dataloader[phase], disable=True):
            inputs = inputs.to(device)
            labels = labels.long().squeeze().to(device)

            with torch.set_grad_enabled(phase == 'train'):
                outputs = model(inputs).squeeze()
                loss = criterion(outputs, labels)

                if phase == 'train':
                    optimizer.zero_grad()
                    loss.backward()
                    optimizer.step()

            running_loss += loss.item() * inputs.size(0)
            preds = torch.max(softmax(outputs), 1)[1]
            y_trues = np.append(y_trues, labels.data.cpu().numpy())
            y_preds = np.append(y_preds, preds.cpu())

        # if phase == 'train':
        #     scheduler.step()

        epoch_loss = running_loss / dataset_sizes[phase]

        print("[{}] Epoch: {}/{} Loss: {} LR: {}".format(
            phase, epoch + 1, num_epochs, epoch_loss, scheduler.get_last_lr()), flush=True)
        print('\nconfusion matrix\n' + str(confusion_matrix(y_trues, y_preds)))
        print('\naccuracy\t' + str(accuracy_score(y_trues, y_preds)))

torch.save(model, "model-v2.pt")


Device being used: cuda
{'train': 5698, 'test': 1784}


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 1/100 Loss: 0.9905852909337516 LR: [0.001]

confusion matrix
[[ 135    1  149   89]
 [  12    0  134   67]
 [  41    2 1592  982]
 [  23    3 1352 1116]]

accuracy	0.49894699894699895


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 1/100 Loss: 1.1688555027337353 LR: [0.001]

confusion matrix
[[  2   0   2   0]
 [ 22   0  62   0]
 [190   0 692   0]
 [174   0 638   2]]

accuracy	0.3901345291479821


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 2/100 Loss: 0.899705556138602 LR: [0.001]

confusion matrix
[[ 243    0  114   17]
 [  12    0  135   66]
 [  48    0 1737  832]
 [  28    0 1403 1063]]

accuracy	0.534047034047034


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 2/100 Loss: 0.9474060083718577 LR: [0.001]

confusion matrix
[[  1   0   0   3]
 [  3   0  26  55]
 [ 43   0 286 553]
 [ 40   0 196 578]]

accuracy	0.4848654708520179


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 3/100 Loss: 0.8556227897208546 LR: [0.001]

confusion matrix
[[ 297    1   63   13]
 [  14    0  146   53]
 [  34    1 1737  845]
 [  12    0 1418 1064]]

accuracy	0.5436995436995437


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 3/100 Loss: 0.8949894230862904 LR: [0.001]

confusion matrix
[[  0   0   3   1]
 [  0   0  23  61]
 [  1   0 184 697]
 [  0   0 137 677]]

accuracy	0.4826233183856502


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 4/100 Loss: 0.8349948858913516 LR: [0.001]

confusion matrix
[[ 299    4   61   10]
 [  14    4  140   55]
 [  16    3 1856  742]
 [  15    1 1406 1072]]

accuracy	0.567041067041067


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 4/100 Loss: 0.9139516300150097 LR: [0.001]

confusion matrix
[[  1   0   0   3]
 [  3   0   4  77]
 [  8   0   5 869]
 [  4   0   0 810]]

accuracy	0.45739910313901344


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 5/100 Loss: 0.7999665517478962 LR: [0.001]

confusion matrix
[[ 335    2   34    3]
 [  10    4  151   48]
 [  19    7 1902  689]
 [   5    1 1428 1060]]

accuracy	0.5793260793260794


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 5/100 Loss: 0.8806130441047686 LR: [0.001]

confusion matrix
[[  0   0   1   3]
 [  4   0   8  72]
 [ 15   0  48 819]
 [ 10   0  16 788]]

accuracy	0.46860986547085204


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 6/100 Loss: 0.7809936280583616 LR: [0.001]

confusion matrix
[[ 356    2   14    2]
 [   7    4  147   55]
 [  15    6 1896  700]
 [   7    2 1381 1104]]

accuracy	0.5896805896805897


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 6/100 Loss: 0.8962355405760453 LR: [0.001]

confusion matrix
[[  1   0   3   0]
 [  0   0  84   0]
 [  0   0 882   0]
 [  1   0 813   0]]

accuracy	0.49495515695067266


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 7/100 Loss: 0.7781438563906883 LR: [0.001]

confusion matrix
[[ 352    2   18    2]
 [  10    3  162   38]
 [  15    9 1973  620]
 [   7    1 1433 1053]]

accuracy	0.5933660933660934


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 7/100 Loss: 0.8605613189962412 LR: [0.001]

confusion matrix
[[  0   0   3   1]
 [  0   0  73  11]
 [  0   0 845  37]
 [  0   0 695 119]]

accuracy	0.5403587443946188


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 8/100 Loss: 0.7694208956927993 LR: [0.001]

confusion matrix
[[ 361    0   11    2]
 [  10    0  165   38]
 [  10    5 1991  611]
 [   6    1 1449 1038]]

accuracy	0.594945594945595


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 8/100 Loss: 0.8664293346650932 LR: [0.001]

confusion matrix
[[  0   0   3   1]
 [  2   0  70  12]
 [ 13   0 837  32]
 [  8   0 703 103]]

accuracy	0.5269058295964125


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 9/100 Loss: 0.7491521500273309 LR: [0.001]

confusion matrix
[[ 367    3    4    0]
 [   9    5  157   42]
 [   3   11 1962  641]
 [   6    1 1375 1112]]

accuracy	0.6047736047736048


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 9/100 Loss: 0.8418472550241402 LR: [0.001]

confusion matrix
[[  0   0   3   1]
 [  0   0  55  29]
 [  1   0 671 210]
 [  0   0 511 303]]

accuracy	0.5459641255605381


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 10/100 Loss: 0.7454399747382385 LR: [0.001]

confusion matrix
[[ 356    0   14    4]
 [   7    9  173   24]
 [   6   13 2130  468]
 [   7    0 1447 1040]]

accuracy	0.6203931203931204


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 10/100 Loss: 0.8862481348450408 LR: [0.001]

confusion matrix
[[  0   0   4   0]
 [  0   3  75   6]
 [  1   4 842  35]
 [  0   0 716  98]]

accuracy	0.5285874439461884


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 11/100 Loss: 0.7514453242748986 LR: [0.001]

confusion matrix
[[ 350    1   17    6]
 [   7   12  173   21]
 [   9   14 2105  489]
 [   7    3 1418 1066]]

accuracy	0.62004212004212


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 11/100 Loss: 0.8678880348601149 LR: [0.001]

confusion matrix
[[  1   0   2   1]
 [  1   0  39  44]
 [  2   0 372 508]
 [  3   0 314 497]]

accuracy	0.4876681614349776


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 12/100 Loss: 0.7364622838311381 LR: [0.001]

confusion matrix
[[ 358    3    6    7]
 [   6   10  170   27]
 [   7   13 2086  511]
 [   9    1 1389 1095]]

accuracy	0.6228501228501229


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 12/100 Loss: 0.8789048099330723 LR: [0.001]

confusion matrix
[[  0   0   2   2]
 [  1   0  48  35]
 [  3   0 421 458]
 [  2   0 326 486]]

accuracy	0.5084080717488789


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 13/100 Loss: 0.7146087796510667 LR: [0.001]

confusion matrix
[[ 367    1    6    0]
 [   8   16  166   23]
 [   6   16 2108  487]
 [   4    1 1323 1166]]

accuracy	0.6418041418041418


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 13/100 Loss: 0.8899341451480249 LR: [0.001]

confusion matrix
[[  0   1   3   0]
 [  0   5  79   0]
 [  0  13 869   0]
 [  2   4 808   0]]

accuracy	0.4899103139013453


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 14/100 Loss: 0.7199907773061567 LR: [0.001]

confusion matrix
[[ 351    1   21    1]
 [   5   22  164   22]
 [   5   13 2052  547]
 [   4    0 1305 1185]]

accuracy	0.6335556335556336


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 14/100 Loss: 0.978017863804984 LR: [0.001]

confusion matrix
[[  0   1   2   1]
 [  5   3  70   6]
 [ 17   1 845  19]
 [ 17   0 720  77]]

accuracy	0.5184977578475336


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 15/100 Loss: 0.6988661303441539 LR: [0.001]

confusion matrix
[[ 363    4    6    1]
 [   8   26  157   22]
 [   5   19 2097  496]
 [   7    1 1238 1248]]

accuracy	0.6553176553176553


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 15/100 Loss: 0.850870547473698 LR: [0.001]

confusion matrix
[[  0   0   2   2]
 [  1   0  38  45]
 [  0   1 380 501]
 [  0   0 238 576]]

accuracy	0.5358744394618834


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 16/100 Loss: 0.6860285465990965 LR: [0.001]

confusion matrix
[[ 368    4    2    0]
 [   5   29  160   19]
 [   6   21 2107  483]
 [   4    2 1225 1263]]

accuracy	0.6611091611091611


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 16/100 Loss: 0.905499862448517 LR: [0.001]

confusion matrix
[[  0   1   0   3]
 [  0   2  33  49]
 [  0   1 282 599]
 [  0   0 157 657]]

accuracy	0.5274663677130045


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 17/100 Loss: 0.661245274340826 LR: [0.001]

confusion matrix
[[ 371    2    0    1]
 [   4   40  146   23]
 [   2   22 2096  497]
 [   6    5 1158 1325]]

accuracy	0.6725166725166725


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 17/100 Loss: 0.8713830649318182 LR: [0.001]

confusion matrix
[[  0   0   3   1]
 [  0   0  53  31]
 [  0   0 666 216]
 [  0   0 483 331]]

accuracy	0.5588565022421524


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 18/100 Loss: 0.6474383507497941 LR: [0.001]

confusion matrix
[[ 364    6    3    1]
 [   6   43  141   23]
 [   3   27 2123  464]
 [   5    1 1120 1368]]

accuracy	0.6840996840996841


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 18/100 Loss: 0.8632451165551027 LR: [0.001]

confusion matrix
[[  0   0   3   1]
 [  0   1  58  25]
 [  1   1 704 176]
 [  0   0 518 296]]

accuracy	0.5610986547085202


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 19/100 Loss: 0.647589805694516 LR: [0.001]

confusion matrix
[[ 366    2    5    1]
 [   7   49  136   21]
 [   4   22 2061  530]
 [   5    0 1034 1455]]

accuracy	0.6898911898911899


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 19/100 Loss: 1.0335224043962132 LR: [0.001]

confusion matrix
[[  0   1   2   1]
 [  0   8  50  26]
 [  6  22 704 150]
 [  6   7 530 271]]

accuracy	0.5510089686098655


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 20/100 Loss: 0.6333619040872139 LR: [0.001]

confusion matrix
[[ 363    1    8    2]
 [   6   46  144   17]
 [   7   22 2160  428]
 [   7    2 1082 1403]]

accuracy	0.6970866970866971


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 20/100 Loss: 1.0098059876684116 LR: [0.001]

confusion matrix
[[  0   0   3   1]
 [  0   0  72  12]
 [  0   0 807  75]
 [  0   0 658 156]]

accuracy	0.5397982062780269


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 21/100 Loss: 0.6180502682788283 LR: [0.001]

confusion matrix
[[ 369    0    5    0]
 [   5   60  128   20]
 [   1   24 2142  450]
 [   4    2 1051 1437]]

accuracy	0.7034047034047034


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 21/100 Loss: 0.8549978174436252 LR: [0.001]

confusion matrix
[[  0   0   3   1]
 [  0   0  59  25]
 [  0   0 685 197]
 [  0   0 502 312]]

accuracy	0.5588565022421524


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 22/100 Loss: 0.5932615519814761 LR: [0.001]

confusion matrix
[[ 365    3    2    4]
 [   6   66  129   12]
 [   3   17 2209  388]
 [   4    1 1037 1452]]

accuracy	0.7181467181467182


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 22/100 Loss: 2.3810579202768514 LR: [0.001]

confusion matrix
[[  0   2   2   0]
 [  1  31  46   6]
 [  3 319 500  60]
 [  1 205 481 127]]

accuracy	0.3688340807174888


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 23/100 Loss: 0.5928641860894714 LR: [0.001]

confusion matrix
[[ 365    2    5    2]
 [  11   61  121   20]
 [   4   18 2168  427]
 [   3    2  984 1505]]

accuracy	0.7193752193752194


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 23/100 Loss: 1.2087765849725816 LR: [0.001]

confusion matrix
[[  0   0   3   1]
 [  0   0  65  19]
 [  0   5 792  85]
 [  0   3 640 171]]

accuracy	0.5397982062780269


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 24/100 Loss: 0.5720933968081636 LR: [0.001]

confusion matrix
[[ 364    6    4    0]
 [  12   63  122   16]
 [   1   19 2144  453]
 [   2    3  880 1609]]

accuracy	0.7335907335907336


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 24/100 Loss: 0.9239076262365008 LR: [0.001]

confusion matrix
[[  0   1   2   1]
 [  0   2  60  22]
 [  1   3 763 115]
 [  0   0 601 213]]

accuracy	0.5482062780269058


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[train] Epoch: 25/100 Loss: 0.5743708532550704 LR: [0.001]

confusion matrix
[[ 358    2   11    3]
 [   7   76  117   13]
 [   2   23 2218  374]
 [   3    5  909 1577]]

accuracy	0.7421902421902422


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


[test] Epoch: 25/100 Loss: 1.0169354619065742 LR: [0.001]

confusion matrix
[[  0   1   2   1]
 [  0   5  70   9]
 [  2   9 759 112]
 [  6  11 669 128]]

accuracy	0.5


/tmp/ipykernel_5995/1896814468.py:66: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


In [5]:
torch.version.cuda

'11.5'

In [6]:
model_loaded = torch.load("model-aug.pt") 

In [ ]:
[[  0   1   2   1]
 [  0   2  60  22]
 [  1   3 763 115]
 [  0   0 601 213]]


In [17]:
def calculate_metrics(confusion_matrix):
    # Assuming confusion_matrix is a 2D list of shape (n, n)
    n = len(confusion_matrix)

    # Calculate True Positives, False Positives, False Negatives, and True Negatives
    tp = [confusion_matrix[i][i] for i in range(n)]
    fp = [sum(confusion_matrix[j][i] for j in range(n) if j != i) for i in range(n)]
    fn = [sum(confusion_matrix[i][j] for j in range(n) if j != i) for i in range(n)]
    tn = [sum(confusion_matrix[i][j] for j in range(n) for i in range(n)) - tp[i] - fp[i] - fn[i] for i in range(n)]

    # Calculate Precision, Recall, and Accuracy
    precision = [tp[i] / (tp[i] + fp[i]) if (tp[i] + fp[i]) != 0 else 0 for i in range(n)]
    recall = [tp[i] / (tp[i] + fn[i]) if (tp[i] + fn[i]) != 0 else 0 for i in range(n)]
    accuracy = sum(tp[i] + tn[i] for i in range(n)) / sum(sum(row) for row in confusion_matrix)

    return precision, recall, accuracy

# Example usage:
confusion_matrix = [
    [  0 ,1 ,2 ,1],
    [  0,2,60,22],
    [  1,3,763,115],
    [  0,0,601,213]
]

precision, recall, accuracy = calculate_metrics(confusion_matrix)

print("Precision:", precision)
print("Recall:", recall)
print("Accuracy:", accuracy)


Precision: [0.0, 0.3333333333333333, 0.5350631136044881, 0.6068376068376068]
Recall: [0.0, 0.023809523809523808, 0.8650793650793651, 0.2616707616707617]
Accuracy: 3.096412556053812


In [28]:
import numpy as np

def calculate_metrics(confusion_matrix):
    true_positives = np.diag(confusion_matrix)
    false_positives = np.sum(confusion_matrix, axis=0) - true_positives
    false_negatives = np.sum(confusion_matrix, axis=1) - true_positives
    true_negatives = np.sum(confusion_matrix) - (true_positives + false_positives + false_negatives)

    accuracy = (true_positives + true_negatives) / np.sum(confusion_matrix)
    precision = true_positives / (true_positives + false_positives)
    recall = true_positives / (true_positives + false_negatives)

    print(np.sum(true_positives+true_negatives) / np.sum(confusion_matrix) ) 

    return accuracy, precision, recall

In [29]:
calculate_metrics(np.array(confusion_matrix))

3.096412556053812


(array([0.99719731, 0.95179372, 0.56165919, 0.58576233]),
 array([0.        , 0.33333333, 0.53506311, 0.60683761]),
 array([0.        , 0.02380952, 0.86507937, 0.26167076]))

In [ ]:
0.48
0.381

In [32]:
conf_matrix_combines = [
    [   1,0,3],
    [   3,6,75],
    [  13,24,1659]
]

In [33]:
calculate_metrics(np.array(conf_matrix_combines))

2.867713004484305


(array([0.98934978, 0.94282511, 0.93553812]),
 array([0.05882353, 0.2       , 0.95509499]),
 array([0.25      , 0.07142857, 0.97818396]))

In [ ]:
0.40
0.43

In [5]:
print('\naccuracy\t' + str(accuracy_score(y_trues, y_preds)))


accuracy	0.5061659192825112


In [6]:
print('\nconfusion matrix\n' + str(confusion_matrix(y_trues, y_preds)))


confusion matrix
[[  0   0   1   3]
 [  0   2  33  49]
 [  2   0 378 502]
 [  2   1 288 523]]


In [31]:
# y_true_mod 
print('\nconfusion matrix\n' + str(confusion_matrix(y_trues, y_preds)))


confusion matrix
[[  1   0   0   3]
 [  3   6  33  42]
 [  6  14 319 543]
 [  7  10 269 528]]


In [24]:
import numpy as np

y_true_mod = np.copy(y_trues)
y_pred_mod = np.copy(y_preds)

y_true_mod[y_true_mod==3] = 2
y_pred_mod[y_pred_mod==3] = 2

In [25]:
print('\naccuracy\t' + str(accuracy_score(y_true_mod, y_pred_mod)))


accuracy	0.9338565022421524


In [27]:
print('\nconfusion matrix\n' + str(confusion_matrix(y_true_mod, y_pred_mod)))


confusion matrix
[[   1    0    3]
 [   3    6   75]
 [  13   24 1659]]


In [30]:
unique_values, counts = np.unique(y_trues, return_counts=True)

# Combine unique values and counts
unique_with_counts = np.column_stack((unique_values, counts))

print("Unique Values with Counts:")
print(unique_with_counts)

Unique Values with Counts:
[[  0.   4.]
 [  1.  84.]
 [  2. 882.]
 [  3. 814.]]


In [16]:
import os
from torch.optim.lr_scheduler import StepLR
from tqdm import tqdm
import torch
from torch import nn, optim
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score

import numpy as np

# from ResTCN import ResTCN
from ResTCN import ResTCN

torch.manual_seed(0)
num_epochs = 1
batch_size = 4
lr = .001
use_cuda = True
device = torch.device("cuda" if use_cuda else "cpu")
print("Device being used:", device, flush=True)


dataloader = get_dataloader(batch_size,
                            'Train.csv',
                            os.path.join(os.getcwd()),
                            'Test.csv',
                            os.path.join(os.getcwd()))
dataset_sizes = {x: len(dataloader[x].dataset) for x in ['train', 'test']}
print(dataset_sizes, flush=True)


model = ResTCN().to(device)
# optimizer = optim.Adam(model.parameters(), lr=lr)
optimizer = optim.SGD(model.parameters(), lr=lr, momentum=0.9)
scheduler = StepLR(optimizer, step_size=50, gamma=.1)

criterion = nn.CrossEntropyLoss().to(device)
softmax = nn.Softmax()

for epoch in range(num_epochs):

    for phase in ['train', 'test']:

        running_loss = .0
        y_trues = np.empty([0])
        y_preds = np.empty([0])

        if phase == 'train':
            model.train()
        else:
            model.eval()

        for inputs, labels in tqdm(dataloader[phase], disable=True):
            inputs = inputs.to(device)
            labels = labels.long().squeeze().to(device)

            with torch.set_grad_enabled(phase == 'train'):
                outputs = model(inputs).squeeze()
                loss = criterion(outputs, labels)

                if phase == 'train':
                    optimizer.zero_grad()
                    loss.backward()
                    optimizer.step()

            running_loss += loss.item() * inputs.size(0)
            preds = torch.max(softmax(outputs), 1)[1]
            y_trues = np.append(y_trues, labels.data.cpu().numpy())
            y_preds = np.append(y_preds, preds.cpu())

        # if phase == 'train':
        #     scheduler.step()

        epoch_loss = running_loss / dataset_sizes[phase]

        print("[{}] Epoch: {}/{} Loss: {} LR: {}".format(
            phase, epoch + 1, num_epochs, epoch_loss, scheduler.get_last_lr()), flush=True)
        print('\nconfusion matrix\n' + str(confusion_matrix(y_trues, y_preds)))
        print('\naccuracy\t' + str(accuracy_score(y_trues, y_preds)))

# torch.save(model, "model-v2.pt")


In [12]:
import os
from torch.optim.lr_scheduler import StepLR
from tqdm import tqdm
import torch
from torch import nn, optim
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score

import numpy as np

# from ResTCN import ResTCN
from ResTCN import ResTCN

torch.manual_seed(0)
num_epochs = 1
batch_size = 4
lr = .001
use_cuda = True
device = torch.device("cuda" if use_cuda else "cpu")
print("Device being used:", device, flush=True)

dataloader = get_dataloader(batch_size,
                            'Train.csv',
                            os.path.join(os.getcwd()),
                            'Test.csv',
                            os.path.join(os.getcwd()))
dataset_sizes = {x: len(dataloader[x].dataset) for x in ['train', 'test']}
print(dataset_sizes, flush=True)


model = ResTCN().to(device)
# optimizer = optim.Adam(model.parameters(), lr=lr)
optimizer = optim.SGD(model.parameters(), lr=lr, momentum=0.9)
scheduler = StepLR(optimizer, step_size=50, gamma=.1)

criterion = nn.CrossEntropyLoss().to(device)
softmax = nn.Softmax()

model.train()

phases = ["train","test"]

for phase in phases:
    running_loss = .0
    y_trues = np.empty([0])
    y_preds = np.empty([0])

    if phase == 'train':
        model.train()
    else:
        model.eval()
        
    for inputs, labels in tqdm(dataloader[phase], disable=True):
        inputs = inputs.to(device)
        print("printing input shape")
        print(inputs.shape)
        labels = labels.long().squeeze().to(device)
    
        with torch.set_grad_enabled(phase == 'train'):
            outputs = model(inputs).squeeze()
            print(outputs.shape)
            loss = criterion(outputs, labels)
    
            if phase == 'train':
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()
    
        running_loss += loss.item() * inputs.size(0)
        preds = torch.max(softmax(outputs), 1)[1]
        y_trues = np.append(y_trues, labels.data.cpu().numpy())
        y_preds = np.append(y_preds, preds.cpu())
        print("DONE")
        break

Device being used: cuda
{'train': 5698, 'test': 1784}
In init
printing input shape
torch.Size([4, 16, 3, 224, 224])
printing z before transpose
tensor([[[ 2.6490e-01,  6.4568e-01, -7.6464e-01,  ...,  1.2411e+00,
          -4.1636e-01, -8.9891e-01],
         [ 2.3127e-01,  6.1020e-01, -8.0479e-01,  ...,  1.3152e+00,
          -4.3911e-01, -9.0772e-01],
         [ 2.5385e-01,  6.9333e-01, -8.1505e-01,  ...,  1.2990e+00,
          -4.7975e-01, -8.8040e-01],
         ...,
         [ 2.2413e-01,  8.3650e-01, -8.1287e-01,  ...,  1.4418e+00,
          -4.6848e-01, -8.1583e-01],
         [ 1.9923e-01,  7.4005e-01, -7.5658e-01,  ...,  1.3353e+00,
          -4.4813e-01, -7.9885e-01],
         [ 2.0489e-01,  6.7177e-01, -7.4626e-01,  ...,  1.3351e+00,
          -4.2609e-01, -7.8578e-01]],

        [[-9.9288e-01,  2.0541e-01, -7.2315e-01,  ...,  1.3025e+00,
          -5.5616e-01, -1.4155e+00],
         [-1.0772e+00,  2.2200e-01, -7.1238e-01,  ...,  1.2330e+00,
          -5.6015e-01, -1.4154e+00],


/tmp/ipykernel_1951303/260619403.py:69: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = torch.max(softmax(outputs), 1)[1]


DONE
printing input shape
torch.Size([4, 16, 3, 224, 224])
printing z before transpose
tensor([[[-9.0812e-01,  3.2425e-01, -1.1335e+00,  ...,  1.5738e+00,
          -2.2343e-02, -3.0762e-01],
         [-8.7166e-01,  2.7194e-01, -1.1368e+00,  ...,  1.6885e+00,
          -1.9232e-02, -3.0282e-01],
         [-7.7375e-01,  3.2274e-01, -1.1702e+00,  ...,  1.5743e+00,
          -3.5321e-02, -2.4089e-01],
         ...,
         [-1.0045e+00,  4.2009e-01, -1.2452e+00,  ...,  1.6912e+00,
          -1.4274e-01, -1.3128e-01],
         [-9.1295e-01,  4.7431e-01, -1.2426e+00,  ...,  1.6927e+00,
          -5.3225e-02,  1.4605e-03],
         [-8.1339e-01,  4.2340e-01, -1.1836e+00,  ...,  1.6204e+00,
           6.6551e-02, -1.4055e-02]],

        [[-6.9904e-01,  5.8570e-01, -1.4385e+00,  ...,  2.4265e+00,
           6.8996e-02, -9.4630e-01],
         [-6.5677e-01,  5.7836e-01, -1.4893e+00,  ...,  2.4733e+00,
          -6.1878e-02, -9.9188e-01],
         [-6.6010e-01,  5.8102e-01, -1.4218e+00,  ...,  2

In [5]:
vals = torch.randn([4,2,3])
vals

tensor([[[ 2.0338,  0.0901, -0.1384],
         [-0.2649,  0.0132, -0.1543]],

        [[ 0.4264,  0.4951,  0.0973],
         [-0.5939,  0.8031,  0.7879]],

        [[-1.2858,  0.5795,  1.2327],
         [ 0.9387, -1.4228, -1.0053]],

        [[ 1.7012,  2.7311, -0.2984],
         [-1.1312,  0.3651,  0.8213]]])

In [6]:
torch.sum(vals, dim=2)

tensor([[ 1.9854, -0.4060],
        [ 1.0189,  0.9971],
        [ 0.5264, -1.4894],
        [ 4.1340,  0.0552]])

In [7]:
model

ResTCN(
  (tcn): TemporalConvNet(
    (network): Sequential(
      (0): TemporalBlock(
        (conv1): Conv1d(32, 128, kernel_size=(7,), stride=(1,), padding=(6,))
        (chomp1): Chomp1d()
        (relu1): ReLU()
        (dropout1): Dropout(p=0.1, inplace=False)
        (conv2): Conv1d(128, 128, kernel_size=(7,), stride=(1,), padding=(6,))
        (chomp2): Chomp1d()
        (relu2): ReLU()
        (dropout2): Dropout(p=0.1, inplace=False)
        (net): Sequential(
          (0): Conv1d(32, 128, kernel_size=(7,), stride=(1,), padding=(6,))
          (1): Chomp1d()
          (2): ReLU()
          (3): Dropout(p=0.1, inplace=False)
          (4): Conv1d(128, 128, kernel_size=(7,), stride=(1,), padding=(6,))
          (5): Chomp1d()
          (6): ReLU()
          (7): Dropout(p=0.1, inplace=False)
        )
        (downsample): Conv1d(32, 128, kernel_size=(1,), stride=(1,))
        (relu): ReLU()
      )
      (1): TemporalBlock(
        (conv1): Conv1d(128, 128, kernel_size=(7,), 